version: '3.7'
services:
  db:
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build: .
    restart: always
    volumes:
      - '.:/app'
      - '/app/tmp/pids/'
    ports:
      - '3000:3000'
    command: '/app/web_entry.sh'
    stdin_open: true
    tty: true
    depends_on:
      - db
volumes:
  db-data: 